### ISSUE TITLE
showAccountLedger: Date arguments don't work

### ISSUE THREAD

**Issue by js931** [peshay/btcde#32]
It doesn't matter if i pass a date argument (date_start / date_end) or not, the function always returns the default, which is the account ledger for the last 10 days.

Example code:
`ledger = conn.showAccountLedger(currency="eth", date_start="2018-01-01T01:00:00+01:00", date_end="2018-01-07T01:00:00+01:00")`

**Comment by TripelB** [comment]
Experiencing the same problem with the date parameters  but in fact it only shows up to three trades. Is there some efficient workaround / solution to this problem?

**Comment by MarcelBeining** [comment]
I do not know if this relates to a problem what I just found, but you have to replace the "+" in the date with its url-encoded form "%2b", otherweise the created URL has problems. It would be good if the btcde class could automatically translate the date (and all other possible parameters) into URL-conform strings!

**Comment by peshay** [comment]
#38 could you please test the version in branch 2.3? If it then fixes your issue I would start a new release.

**Comment by MarcelBeining** [comment]
Sorry for the delay, forgot about it.
Actually I found another problem that causes this behavior:
According to the bitcoin.de API documentation, the parameter names are `datetime_start `and `datetime_end` but your `showAccountLedger` method actually uses `date_start` and `date_end` to create the URI !!
The bitcoin.de support team told me this, as they saw that my requests have `date_start `instead of `datetime_start `parameter which thus gets not parsed by their API resulting in default behavior. So simply change `avail_params `in line 305 in `btcde.py` :-)

**Comment by peshay** [comment]
Could you create a pull request for that change?

**Comment by peshay** [comment]
@MarcelBeining Please test current master branch, if all works as expected, I'll draft a new release.

**Comment by MarcelBeining** [comment]
@peshay : I tested showAccount ledger and it works now as expected. 
However, I have another problem but for this I open a new issue.
Thanks!

**Comment by MarcelBeining** [comment]
ok I just found out that my problem was already there (#31 ) :-D
